# Generated by Django 4.2.6 on 2023-10-21 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notlar',
            name='durum',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='notlar',
            name='ortalama',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
