# Generated by Django 4.2.6 on 2023-10-22 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0002_alter_notlar_durum_alter_notlar_ortalama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notlar',
            name='ortalama',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True),
        ),
        migrations.AlterField(
            model_name='ogrenciler',
            name='ogrenciKulup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ogrenci.kulupler'),
        ),
    ]
