# Generated by Django 4.2.6 on 2023-11-11 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0004_remove_notlar_ogrenciid_notlar_ogrenciid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notlar',
            name='ogrenciId',
        ),
        migrations.AddField(
            model_name='notlar',
            name='ogrenciId',
            field=models.ManyToManyField(to='ogrenci.ogrenciler'),
        ),
    ]
