# Generated by Django 4.2.6 on 2023-11-12 09:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0005_remove_notlar_ogrenciid_notlar_ogrenciid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notlar',
            name='dersId',
        ),
        migrations.RemoveField(
            model_name='notlar',
            name='ogrenciId',
        ),
        migrations.AddField(
            model_name='notlar',
            name='dersId',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ogrenci.dersler'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notlar',
            name='ogrenciId',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='ogrenci.ogrenciler'),
            preserve_default=False,
        ),
    ]
