# Generated by Django 4.2.6 on 2023-11-12 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0006_remove_notlar_dersid_remove_notlar_ogrenciid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notlar',
            name='dersId',
        ),
        migrations.RemoveField(
            model_name='notlar',
            name='ogrenciId',
        ),
        migrations.AddField(
            model_name='notlar',
            name='dersId',
            field=models.ManyToManyField(to='ogrenci.dersler'),
        ),
        migrations.AddField(
            model_name='notlar',
            name='ogrenciId',
            field=models.ManyToManyField(to='ogrenci.ogrenciler'),
        ),
    ]
